version: '3'

services:
  nginx:
    image: nginx
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available/
      - ./docker/logs/nginx/:/var/log/nginx
      # - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    environment:
      - NGINX_HOST=gsbd.test
      - NGINX_PORT=80
    networks:
    - sail


    php-fpm:
        build:
            context: "./docker/php-fpm"
        volumes:
            - ./:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
        networks:
            - sail
        expose:
            - "9000"



# Network
networks:
    sail:
        driver: bridge