version: '3'

services:
  nginx:
    image: nginx
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available/
      - ./docker/logs/nginx/:/var/log/nginx
    ports:
      - '80:80'
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    # networks:
    #   - sail



    # php-fpm:
    #     build:
    #         context: './docker/php-fpm'
    #     volumes:
    #         - ./:/var/www:cached
    #     networks:
    #         - sail
    #     expose:
    #         - '9000'



# Network
# networks:
#     sail:
#         driver: bridge