version: '3'

services:
  nginx:
    build:
      context: ./docker/nginx  # Custom Dockerfile location
    container_name: hybrid_nginx  # Custom name for the Nginx container
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available/
      - ./docker/logs/nginx/:/var/log/nginx
    ports:
      - '9000:9000'
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=9000
    networks:
      - sail

  php-fpm:
    build:
      context: './docker/php-fpm'  # Custom Dockerfile location
    container_name: hybrid_php_fpm  # Custom name for the PHP-FPM container
    volumes:
      - ./:/var/www:cached
    networks:
      - sail
    expose:
      - '9000'

networks:
  sail:
    driver: bridge